# fi=open('test.txt','r')
# print(fi.read())
# f=open('tarning.txt','w')
# f.write('i am taking traning from basket')
# f.close()
# f=open('traning', 'a')
# f_1=open('aaa.txt','r')
# print(f_1.read())
# f_1.close()
f_1=open('aaa.txt','a')
f_1.write('\n this is my file')
f_1=open('aaa.txt','r')
print(f_1.read)